# Generated by Django 2.2.7 on 2019-11-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField()),
                ('dept', models.CharField(choices=[('Mech', 'Mechanical Engineering'), ('Civil', 'Civil Engineering'), ('CSE', 'Computer Science Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communications Engineering'), ('EEE', 'Electrical & Electronics Engineering')], max_length=50)),
            ],
        ),
    ]
