# Generated by Django 2.2.7 on 2019-11-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='remarks',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
    ]
