# Generated by Django 2.2.7 on 2019-11-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20191107_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
