# Generated by Django 2.2.7 on 2019-11-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('SUV', 'Sports Utility Vehicle'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Mini SUV', 'Mini Sports Utility Vehicle'), ('Sports Car', 'Sports Car')], max_length=200)),
                ('make', models.CharField(choices=[('Lamborghini', 'Lamborghini'), ('Alfa Romeo', 'Alfa Romeo'), ('Lexus', 'Lexus'), ('Cadillac', 'Cadillac'), ('Bentley', 'Bentley'), ('Range Rover', 'Range Rover'), ('Jaguar', 'Jaguar'), ('Renault', 'Renault'), ('Suzuki', 'Maruti Suzuki'), ('Mahindra', 'Mahindra'), ('Tata', 'Tata'), ('Fiat', 'Fiat'), ('Datsun', 'Datsun'), ('Ford', 'Ford'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Maserati', 'Maserati'), ('Audi', 'Audi'), ('Volkswagon', 'Volkswagon'), ('BMW', 'BMW'), ('Mini', 'Mini')], max_length=200)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
